pipeline {
    agent any

    stages {
        stage('Unit tests - backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                GOCACHE    = "${WORKSPACE}/.go-cache"
                GOMODCACHE = "${WORKSPACE}/.go-mod-cache"
            }
            steps {
                dir('bugtracker-backend') {
                    sh '''
                        mkdir -p $GOCACHE $GOMODCACHE
                        go test -v ./...
                    '''
                }
            }
        }
    }
}
